export const packages = [
  {
    id: 1,
    name: "Quick Browse",
    duration: "1 Hour",
    price: 10,
    speed: "2 Mbps",
    features: ["Basic browsing", "Social media", "Email access", "Standard support"],
    color: "yellow",
    popular: false,
    description: "Perfect for quick internet access and basic browsing needs.",
  },
  {
    id: 2,
    name: "Work Session",
    duration: "4 Hours",
    price: 15,
    speed: "3 Mbps",
    features: ["Video calls", "File downloads", "Streaming (SD)", "Priority support"],
    color: "green",
    popular: false,
    description: "Ideal for work sessions, video calls, and moderate usage.",
  },
  {
    id: 3,
    name: "Half Day",
    duration: "12 Hours",
    price: 20,
    speed: "4 Mbps",
    features: ["HD streaming", "Large downloads", "Gaming", "24/7 support"],
    color: "purple",
    popular: false,
    description: "Great for extended usage with faster speeds and HD streaming.",
  },
  {
    id: 4,
    name: "Full Day",
    duration: "24 Hours",
    price: 30,
    speed: "5 Mbps",
    features: ["Ultra-fast browsing", "4K streaming", "Unlimited downloads", "Premium support"],
    color: "blue",
    popular: true,
    description: "Our most popular package with maximum speed and unlimited access.",
  },
]
